name: Build Angular

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false,
            imagekit: {
              urlEndpoint: '${{ secrets.IMAGEKIT_URL_ENDPOINT }}',
              publicKey: '${{ secrets.IMAGEKIT_PUBLIC_KEY }}'
            },
            apiUrl: 'http://localhost:3000'
          };" > src/environments/environment.ts
          echo "export const environment = {
            production: true,
            imagekit: {
              urlEndpoint: '${{ secrets.IMAGEKIT_URL_ENDPOINT }}',
              publicKey: '${{ secrets.IMAGEKIT_PUBLIC_KEY }}'
            },
            apiUrl: '${{ secrets.API_URL }}'
          };" > src/environments/environment.production.ts

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Commit dist
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/
          git commit -m "build [skip ci]" || echo "Nothing to commit"
          git push
